### ISSUE TITLE
Set up MVD fork repository

### ISSUE THREAD

**Issue by ouphi** [edc-oneweek/MinimumViableDataspace#9]
# Description
Set up MVD fork repository to be able to run CD workflow. Be able to deploy and destroy MVD easily.

## Acceptance criteria
- [ ] CD can run when creating PRs.
- [ ] User can trigger Deploy workflow and Destroy workflow and it works.

## Tasks
- [x] Fork MVD in edc-oneweek organization
- [ ] Create Apps & add federated credentials
- [ ] Set up secrets and config
- [ ] Test that CD, Deploy and Destroy workflows work
